"""Private worker boundary: the authenticated backend owns source/work paths."""
import math
import re
from pathlib import Path

ASPECTS = {'9:16': 9 / 16, '16:9': 16 / 9, '1:1': 1}
LAYOUTS = {'auto', 'general', 'screencast', 'wide', 'speaker-cut'}
CAPTION_STYLES = {'karaoke', 'classic', 'neon', 'pop', 'box'}
HOOK_STYLES = {'pill', 'classic', 'dark', 'yellow', 'red', 'outline', 'outline_yellow'}


def number(value, label, low, high):
    if isinstance(value, bool) or not isinstance(value, (float, int)) or not math.isfinite(value):
        raise ValueError(label + ' must be finite')
    if value < low or value > high:
        raise ValueError(label + ' outside permitted bounds')
    return value


def validate(request):
    if not isinstance(request, dict):
        raise ValueError('request must be an object')
    if not re.fullmatch(r'[a-zA-Z0-9_-]{1,128}', request.get('jobId', '')):
        raise ValueError('invalid jobId')
    if request.get('operation') not in ('clips', 'edit'):
        raise ValueError('unsupported operation')
    if request.get('aspectRatio') not in ASPECTS or request.get('layout') not in LAYOUTS:
        raise ValueError('unsupported aspectRatio or layout')
    source, workdir = Path(request['sourcePath']), Path(request['workDir'])
    if not source.is_absolute() or not workdir.is_absolute():
        raise ValueError('sourcePath and workDir must be absolute backend paths')
    if "'" in str(workdir) or '\n' in str(workdir):
        raise ValueError('unsafe concat working path')
    if source.is_symlink() or workdir.is_symlink():
        raise ValueError('symlink source/workdir is not permitted')
    source = source.resolve(strict=True)
    if not source.is_file():
        raise ValueError('source is not a regular file')
    workdir.mkdir(parents=True, exist_ok=True)
    workdir = workdir.resolve(strict=True)
    if workdir == Path('/'):
        raise ValueError('workDir cannot be filesystem root')
    for field, styles in [('captions', CAPTION_STYLES), ('hook', HOOK_STYLES)]:
        option = request.get(field, {})
        if not isinstance(option, dict) or not isinstance(option.get('enabled', False), bool):
            raise ValueError('invalid ' + field)
        if option.get('enabled') and option.get('style', 'karaoke' if field == 'captions' else 'pill') not in styles:
            raise ValueError('unsupported ' + field + ' style')
    from caption_options import validate as validate_captions
    validate_captions(request.get('captions', {}))
    if len(str(request.get('designBrief', ''))) > 4000 or len(str(request.get('hook', {}).get('text', ''))) > 500:
        raise ValueError('text exceeds limit')
    if 'durationSeconds' in request.get('hook', {}):
        number(request['hook']['durationSeconds'], 'hook durationSeconds', 0.1, 14400)
    audio = request.get('audio', {})
    if audio.get('mode', 'keep') not in ('keep', 'mute', 'mix-narration', 'replace-narration'):
        raise ValueError('unsupported audio mode')
    timings = audio.get('narrationCaptions', request.get('narrationCaptions'))
    if timings is not None:
        if not isinstance(timings,list) or len(timings)>10000:
            raise ValueError('invalid narration captions')
        previous = 0
        for entry in timings:
            if not isinstance(entry,dict) or not isinstance(entry.get('text'),str) or not 0<len(entry['text'])<=2000:
                raise ValueError('invalid narration caption text')
            start=number(entry.get('startMs'),'narration caption startMs',previous,21600000)
            previous=number(entry.get('endMs'),'narration caption endMs',start+1,21600000)
        declared=audio.get('narrationDurationSeconds',request.get('narrationDurationSeconds'))
        if declared is not None:
            number(declared,'narration duration',previous/1000,21600)
    for field in ('narrationPath', 'bgmPath'):
        if audio.get(field):
            path = Path(audio[field]).resolve(strict=True)
            if not path.is_file() or not path.is_relative_to(workdir):
                raise ValueError('audio artifact must belong to workDir')
    if audio.get('mode', 'keep') in ('mix-narration', 'replace-narration') and not audio.get('narrationPath') and request.get('phase', 'all') != 'analyze':
        raise ValueError('narration audio must be generated by the backend before rendering')
    if request.get('phase', 'all') not in ('all', 'analyze', 'render'):
        raise ValueError('unsupported worker phase')
    selection = {'count':3,'minSeconds':15,'maxSeconds':60,**request.get('selection',{})}
    number(selection.get('count'), 'count', 1, 15)
    if int(selection['count']) != selection['count']:
        raise ValueError('count must be an integer')
    number(selection.get('minSeconds'), 'minSeconds', 0.5, 180)
    number(selection.get('maxSeconds'), 'maxSeconds', selection['minSeconds'], 180)
    overrides = request.get('cropOverrides', {})
    if not isinstance(overrides, dict) or len(overrides) > 100:
        raise ValueError('invalid cropOverrides')
    def centre(value):
        if isinstance(value, dict):
            if set(value) != {'x', 'y'}: raise ValueError('crop centre requires x/y')
            number(value['x'], 'crop x', 0, 1); number(value['y'], 'crop y', 0, 1)
        else:
            number(value, 'crop centre', 0, 1)
    for key, value in overrides.items():
        if not str(key).isdigit() or int(key) > 10000: raise ValueError('invalid scene index')
        if isinstance(value, dict) and set(value) == {'top', 'bottom'}:
            centre(value['top']); centre(value['bottom'])
        else:
            number(value, 'crop centre', 0, 1)
    request['selection'] = selection
    return source, workdir


def segments(values, duration, max_total=180):
    if not isinstance(values, list) or not 1 <= len(values) <= 12:
        raise ValueError('segments must contain 1 to 12 entries')
    clean = []
    for item in values:
        start = number(item.get('startSeconds'), 'startSeconds', 0, duration)
        end = number(item.get('endSeconds'), 'endSeconds', start + 0.5, duration)
        clean.append({'start': start, 'end': end})
    if sum(s['end'] - s['start'] for s in clean) > max_total:
        raise ValueError('clip exceeds maximum permitted duration')
    return clean
